fix: stop double counting rewatched
openedx/aspects-dbt pull request #135
Opened 2024-11-20 17:46 UTC by saraburns1

fix query to keep watched time when rewatched, and stop double counting rewatched time

2024-11-20 18:15 UTC, bmtcril commented
Closing and reopening since CLA check seems wedged

2024-11-20 21:32 UTC, Ian2012 approved these changes

2024-11-21 13:45 UTC, bmtcril requested changes
Looks like this still has some issues with calculations or catching updated. We're looking at it more today.

2024-11-26 18:41 UTC, bmtcril approved these changes

2024-11-26 18:44 UTC, merged